"""
LangGraph workflow definition for the Incede contact bot.
Defines the graph nodes, edges, and conditional routing logic for
collecting and validating user contact information step by step.

All bot replies are generated by the LLM — no hardcoded strings.
"""

from typing import Literal

from langgraph.graph import StateGraph, START, END

from schema import ContactBotState
from nodes import (
    ask_name,
    ask_phone,
    ask_email,
    ask_description,
    llm_node,
    complete_node,
)


# --------------------------------------------------------------------------
# Routing function for conditional edges
# --------------------------------------------------------------------------

def route_after_llm(
    state: ContactBotState,
) -> Literal["ask_name", "ask_phone", "ask_email", "ask_description", "complete"]:
    """
    Conditional edge: determines the next node after llm_node.

    - If the current field is invalid, re-routes to the SAME ask_* node
      (which will NOT generate a new prompt — the reply was already added
      to messages by llm_node).
    - If valid, advances to the next ask_* node or complete.
    """
    current_field = state.get("current_field", "name")
    is_valid = state.get("is_valid", False)

    if not is_valid:
        return {
            "name": "ask_name",
            "phone": "ask_phone",
            "email": "ask_email",
            "description": "ask_description",
        }.get(current_field, "ask_name")

    return {
        "name": "ask_phone",
        "phone": "ask_email",
        "email": "ask_description",
        "description": "complete",
    }.get(current_field, "complete")


# --------------------------------------------------------------------------
# Graph builder
# --------------------------------------------------------------------------

def build_graph() -> StateGraph:
    """
    Build and compile the LangGraph state machine for the contact bot.

    Flow:
        START → ask_name → llm_node → (valid → ask_phone | invalid → ask_name)
        ask_phone → llm_node → (valid → ask_email  | invalid → ask_phone)
        ask_email → llm_node → (valid → ask_description | invalid → ask_email)
        ask_description → llm_node → (valid → complete | invalid → ask_description)
        complete → END
    """
    workflow = StateGraph(ContactBotState)

    workflow.add_node("ask_name", ask_name)
    workflow.add_node("ask_phone", ask_phone)
    workflow.add_node("ask_email", ask_email)
    workflow.add_node("ask_description", ask_description)
    workflow.add_node("llm_node", llm_node)
    workflow.add_node("complete", complete_node)

    workflow.add_edge(START, "ask_name")

    workflow.add_conditional_edges(
        "llm_node",
        route_after_llm,
        {
            "ask_name": "ask_name",
            "ask_phone": "ask_phone",
            "ask_email": "ask_email",
            "ask_description": "ask_description",
            "complete": "complete",
        },
    )

    workflow.add_edge("complete", END)

    workflow.add_edge("ask_name", "llm_node")
    workflow.add_edge("ask_phone", "llm_node")
    workflow.add_edge("ask_email", "llm_node")
    workflow.add_edge("ask_description", "llm_node")

    compiled = workflow.compile()

    graph = compiled.get_graph().draw_mermaid_png()
    with open("graph.png", "wb") as f:
        f.write(graph)

    return compiled


# Singleton compiled graph instance
contact_bot_graph = build_graph()
