"""
LangGraph workflow definition for the Incede contact bot.
Defines the graph nodes, edges, and conditional routing logic for
collecting and validating user contact information step by step.

All bot replies are generated by the LLM — no hardcoded strings.

Checkpointing
-------------
The compiled graph uses a SqliteSaver checkpointer so every node transition
is persisted to disk.  State survives Flask restarts, deploys, and worker
recycles.  Each conversation is identified by thread_id == session_id.

Interrupt strategy
------------------
The graph registers interrupt_before=["llm_node"].  This means:

  start_session  → graph.invoke({initial_state}, config)
                   runs ask_name, then PAUSES before llm_node
                   → caller reads the greeting from the snapshot

  /api/chat      → graph.update_state(config, {"raw_user_input": ..., "messages": ...})
                   graph.invoke(None, config)
                   resumes from llm_node, runs validation + reply, runs next ask_* node,
                   then PAUSES again before the following llm_node call
                   → caller reads the latest bot message from the snapshot
"""

from typing import Literal

from langgraph.graph import StateGraph, START, END
from langgraph.checkpoint.sqlite.sync import SqliteSaver

from schema import ContactBotState
from nodes import (
    ask_name,
    ask_phone,
    ask_email,
    ask_description,
    llm_node,
    complete_node,
)

# Path must match the application database so the checkpointer tables live
# alongside the business-logic tables in one file.
_CHECKPOINT_DB_PATH = "incede_bot.db"


# --------------------------------------------------------------------------
# Routing function for conditional edges
# --------------------------------------------------------------------------

def route_after_llm(
    state: ContactBotState,
) -> Literal["ask_name", "ask_phone", "ask_email", "ask_description", "complete"]:
    """
    Conditional edge: determines the next node after llm_node.

    - If the current field is invalid, re-routes to the SAME ask_* node
      (which will NOT generate a new prompt — the reply was already added
      to messages by llm_node).
    - If valid, advances to the next ask_* node or complete.
    """
    current_field = state.get("current_field", "name")
    is_valid = state.get("is_valid", False)

    if not is_valid:
        return {
            "name": "ask_name",
            "phone": "ask_phone",
            "email": "ask_email",
            "description": "ask_description",
        }.get(current_field, "ask_name")

    return {
        "name": "ask_phone",
        "phone": "ask_email",
        "email": "ask_description",
        "description": "complete",
    }.get(current_field, "complete")


# --------------------------------------------------------------------------
# Graph builder
# --------------------------------------------------------------------------

def build_graph():
    """
    Build and compile the LangGraph state machine for the contact bot.

    Flow:
        START → ask_name → [INTERRUPT] → llm_node → (valid → ask_phone | invalid → ask_name)
        ask_phone → [INTERRUPT] → llm_node → (valid → ask_email  | invalid → ask_phone)
        ask_email → [INTERRUPT] → llm_node → (valid → ask_description | invalid → ask_email)
        ask_description → [INTERRUPT] → llm_node → (valid → complete | invalid → ask_description)
        complete → END

    The interrupt_before=["llm_node"] pauses execution after every ask_* node so
    that the Flask endpoint can return the bot's question to the user and wait
    for the next HTTP request before resuming.

    Returns:
        A compiled CompiledStateGraph wired to a SqliteSaver checkpointer.
    """
    workflow = StateGraph(ContactBotState)

    workflow.add_node("ask_name", ask_name)
    workflow.add_node("ask_phone", ask_phone)
    workflow.add_node("ask_email", ask_email)
    workflow.add_node("ask_description", ask_description)
    workflow.add_node("llm_node", llm_node)
    workflow.add_node("complete", complete_node)

    workflow.add_edge(START, "ask_name")

    workflow.add_conditional_edges(
        "llm_node",
        route_after_llm,
        {
            "ask_name": "ask_name",
            "ask_phone": "ask_phone",
            "ask_email": "ask_email",
            "ask_description": "ask_description",
            "complete": "complete",
        },
    )

    workflow.add_edge("complete", END)

    workflow.add_edge("ask_name", "llm_node")
    workflow.add_edge("ask_phone", "llm_node")
    workflow.add_edge("ask_email", "llm_node")
    workflow.add_edge("ask_description", "llm_node")

    # SqliteSaver stores every checkpoint in the same database file used by
    # the rest of the app.  The context-manager form keeps a single connection
    # open for the lifetime of the process; __exit__ is never called here
    # because this object lives for the full server lifetime.
    checkpointer = SqliteSaver.from_conn_string(_CHECKPOINT_DB_PATH)

    compiled = workflow.compile(
        checkpointer=checkpointer,
        # Pause before llm_node after each ask_* node so the bot's question
        # can be returned to the user before processing their next reply.
        interrupt_before=["llm_node"],
    )

    try:
        graph_png = compiled.get_graph().draw_mermaid_png()
        with open("graph.png", "wb") as f:
            f.write(graph_png)
    except Exception:
        # Drawing is optional; never block startup if it fails.
        pass

    return compiled


# Singleton compiled graph instance — shared across all Flask requests.
# SqliteSaver is thread-safe for concurrent reads; Flask's dev server is
# single-threaded, and gunicorn/uwsgi workers each get their own process
# (and therefore their own SqliteSaver connection), which is safe for SQLite
# WAL mode.
contact_bot_graph = build_graph()